data_path: 'modular_data'
resources_path: 'modular_resources'
external_resources:
# the path to external resources must be absolute, even if by using variables (~, etc.)
  concert_resources_path: '$(rospack find concert_resources)'
  dagana_path: '$(rospack find dagana_urdf)'
  # whatever_resources_path: None
modularbot_path: 'modular_data/ModularBot'
deploy_dir: '~/src/fhi_ws/src'
